### ISSUE TITLE
Configurable floating-point precision 

### ISSUE THREAD

**Issue by vonhoff** [fdefelici/clove-unit#65]
Consider the floating-point precision configuration. Currently, the following assertion returns true with:
```C
CLOVE_FLOAT_EQ(0.00000198765435, 0.00000112345678);
```
Should it be specific to each suite or should it be global?

**Comment by vonhoff** [comment]
It might be an idea to use different floating-point precision for floats and doubles. Because doubles can have a higher precision than floats. Doubles can have a precision of 15 decimal places, while floats can have 7, if I remember correctly. Setting the precision to the highest precision for each type by default might also be an idea.

**Comment by fdefelici** [comment]
Some times ago I added this memorandum:
![image](https://github.com/fdefelici/clove-unit/assets/24794993/8766ff4a-9638-4f18-9681-7c6daafe3668)

Configuring this to the highest precision possibile (even specific for float and double) doesn't address the issue in a clean way, because depending on the use case, you could need less precision to evaluate an assertion.

Floating precision should be user specific and probably not a global configuration. This because even in the same project different tests could need different precisions. So it could be better to provide floating precision argument in FLOAT/DOUBLE assertions. Something like this:

```
CLOVE_FLOAT_EQ_WITH_PRECISION(expected, actual, precision)

//or CLOVE_FLOAT_EQ_P as a shortcut.
```

As a drawback, the number of assertion for float and double will be doubled (the current ones with default, and the ones with precision argument). To be understood if apply precision only to EQ and NE assertions or extends to the other assertion types (GT, GTE, LT, LTE). Currently the default precision is only applied in EQ and NE.

VSCode and VisualStudio ide plugins should not be impacted by this change.

**Comment by fdefelici** [comment]
Implemented floating precision on EQ and NE:
- CLOVE_FLOAT_EQ and CLOVE_FLOAT_NE defaulted to 6 (1E-6) 
- CLOVE_DOUBLE_EQ and CLOVE_DOUBLE_NE defaulted to 15 (1E-15)
- CLOVE_FLOAT_EQ_P, CLOVE_FLOAT_NE_P, CLOVE_DOUBLE_EQ_P, CLOVE_DOUBLE_NE_P allow to specify a custom precision as an unsigned integer 

Futhermore floating precision has been taken into account when reporting float/double assertion failure message on expected and actual value, updating all the report (pretty, json, csv).
Here an example of pretty report for double:
![image](https://github.com/fdefelici/clove-unit/assets/24794993/5336b3e0-a557-4168-9c7c-0ccd48f16fc3)

**Comment by vonhoff** [comment]
Great progress! I'm currently updating the README, I could add the new precision assertions to it.

**Comment by fdefelici** [comment]
Thanks. Readme already updated :)
