### ISSUE TITLE
gcc/clang on linux emit warnings

### ISSUE THREAD

**Issue by omalaspinas** [fdefelici/clove-unit#73]
Hello,

first let me say that this library looks really awesome. Thanks for the great work.

I have nevertheless a slight problem when compiling with `gcc` or `clang` (with `-Wall`, `-Wextra`, and `-pedantic`). There are a very large amount of warnings (unknown-pragmas only with gcc, unused parameters, defined but not used variables, unused variables, etc).

I tested with gcc 11.4 and clang 14.0 on Ubuntu.

Unfortunately this is problematic for use for using in a testing framwork since it pollutes a lot the possible warnings of the actual library one wants to test.

Most problems are related with using linux I think and could be corrected with **a lot** of pre-processing directives spread all over the place.

What would you think about the idea of creating a MR about this?

**Comment by fdefelici** [comment]
Hi @omalaspinas thanks for reporting it.

Yes, contributions are welcome.

Anyhow, I would like to understand how many points need to be fixed and to find the best-way to place the smallest possible number of guards (pre-processing directives).

I'll try to make a test next days.

In the maintime, if you already made the fix and want to share it you could also submit a PR.

**Comment by omalaspinas** [comment]
I haven't prepared a fix yet but only quickly looked at how we could make this work. 

If you have any general guidelines on how to proceed I would be more than happy to make a PR.

**Comment by fdefelici** [comment]
Hi @omalaspinas,

I took the task, to make some enhancement for the project.
I improved CI automation to help with the task and possibly I have applyied the less invasive solutions for the different type of warnings.

From the compilation point of view, now seems 'nice and clean' for C language with GCC and CLANG.
Just a note for C++ language instead: 
- compiling with CLANG++ it's 'warnings free' .
- compiling with G++ < 13 emit warning "unknown pragmas" about '#pragma region'. The fix I applyied for GCC doesn't work because of a bug of G++ compiler that has been addressed only at version 13 (more details here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53431)

If you want to try this fix before the final release, and enventually provide some feedback, you can get clove-unit header from this branch: https://github.com/fdefelici/clove-unit/tree/issue-73-gcc/clang_on_linux_emit_warnings

Futhermore, if you want be notified when the next release will be published including this fix you can join the discord channel: https://discord.gg/Mjx4YRQfFt

**Comment by omalaspinas** [comment]
Hi @fdefelici,

thanks a lot for your work!

I can confirm that the code in the branch <https://github.com/fdefelici/clove-unit/tree/issue-73-gcc-clang_on_linux_emit_warnings> (I think there is a typo in your comment above and I thought there was no modification at first :)) emits almost no warnings. To be more precise:

1. With gcc 13.2.1 no warnings (-Wall -Wextra -pedantic)
2. With clang 16.0.6 (not clang++, I'm more a "C" guy ;)) only one warning:

`./clove-unit.h:45:48: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
__CLOVE_EXTERN_C void __clove_utils_empty_funct();`

There are a few of them. But I find them weird, because there is no obvious reason for this to happen...

**Comment by fdefelici** [comment]
Thanks for your feedback.

about `clang`, I've tested against the version 14 you mentioned at the beginning :)

I'll try to have a look also with `clang v16`

**Comment by omalaspinas** [comment]
Yeah sorry. I'm on two different machines with different configurations apparently :D. I'll also try this evening on my other machine.

Thanks again.

**Comment by fdefelici** [comment]
Improved CI automation to easily support more compilers and versions on the go and made the related fixes.

Currently compilation ends without warnings for the following C compilers:
- gcc: 11, 12, 13
- clang: 13, 14, 15, 16, 17

For C++ compiler same results except for:
- g++ 11 and 12 due to the explination given in the [previous comment](https://github.com/fdefelici/clove-unit/issues/73#issuecomment-1856991726).

@omalaspinas if you want to test again the behaviour you can get the updated clove-unit.h from the same branch.

**Comment by omalaspinas** [comment]
No more warnings!

Thanks!
